version: "3"
services:
  app:
    build:
      context: .
    profiles:
      - app
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: "postgres"
    profiles:
      - app
      - service
    environment:
      - POSTGRES_USER=simple
      - POSTGRES_PASSWORD=simple
      - POSTGRES_DB=simple
    ports:
      - "5432:5432"
