apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      service: database
  replicas: 1
  template:
    metadata:
      labels:
        service: database
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: simple
            - name: POSTGRES_USER
              value: simple
            - name: POSTGRES_PASSWORD
              value: simple
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    service: database
